import type { Metadata } from "next";
import { Alegreya } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
const allegreya = Alegreya({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StackSearch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={allegreya.className}>      <Navbar/>
      {children}</body>
    </html>
  );
}
